package by.monk.skud.monitor;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.KeyEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebResourceError;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.EditText;
import android.widget.Toast;

/**
 * Full-screen Android 5+ kiosk for /monitor.html generated by Monk_SKUD_UNEX.
 * The page data is refreshed every 3 seconds without a visible full-page flash.
 * Long-press the page, or press MENU, to change the monitor URL.
 */
public class MainActivity extends Activity {
    private static final String PREFS = "monitor";
    private static final String KEY_URL = "url";
    private static final long REFRESH_MS = 3000L;

    private final Handler handler = new Handler(Looper.getMainLooper());
    private WebView web;
    private SharedPreferences prefs;
    private boolean active;

    private final Runnable refresher = new Runnable() {
        @Override public void run() {
            if (active && web != null) {
                // monitor.js exports refreshMonitor(). Calling it avoids flicker.
                web.evaluateJavascript("if(window.refreshMonitor){window.refreshMonitor();}else{location.reload();}", null);
                handler.postDelayed(this, REFRESH_MS);
            }
        }
    };

    @Override protected void onCreate(Bundle state) {
        super.onCreate(state);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        prefs = getSharedPreferences(PREFS, MODE_PRIVATE);
        enterKioskMode();
        createWebView();
        String url = prefs.getString(KEY_URL, "");
        if (url == null || url.trim().isEmpty()) showUrlDialog(true);
        else load(url);
    }

    private void createWebView() {
        web = new WebView(this);
        web.setBackgroundColor(Color.rgb(5, 11, 20));
        setContentView(web);
        WebSettings s = web.getSettings();
        s.setJavaScriptEnabled(true);
        s.setDomStorageEnabled(true);
        s.setLoadWithOverviewMode(true);
        s.setUseWideViewPort(true);
        s.setBuiltInZoomControls(false);
        s.setDisplayZoomControls(false);
        s.setCacheMode(WebSettings.LOAD_NO_CACHE);
        s.setMediaPlaybackRequiresUserGesture(false);
        if (android.os.Build.VERSION.SDK_INT >= 21) s.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);
        web.setWebChromeClient(new WebChromeClient());
        web.setWebViewClient(new WebViewClient() {
            @Override public void onPageFinished(WebView view, String url) { restartRefresh(); }
            @Override public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
                scheduleReload();
            }
            @Override public void onReceivedError(WebView view, WebResourceRequest request, WebResourceError error) {
                if (request == null || request.isForMainFrame()) scheduleReload();
            }
        });
        web.setOnLongClickListener(new View.OnLongClickListener() {
            @Override public boolean onLongClick(View v) { showUrlDialog(false); return true; }
        });
    }

    private void load(String value) {
        String url = normalize(value);
        prefs.edit().putString(KEY_URL, url).apply();
        web.loadUrl(url);
    }

    private String normalize(String value) {
        String url = value == null ? "" : value.trim();
        if (!url.startsWith("http://") && !url.startsWith("https://")) url = "http://" + url;
        if (!url.contains("/monitor")) {
            while (url.endsWith("/")) url = url.substring(0, url.length() - 1);
            url += "/monitor.html";
        }
        return url;
    }

    private void showUrlDialog(final boolean required) {
        final EditText input = new EditText(this);
        String current = prefs.getString(KEY_URL, "");
        input.setSingleLine(true);
        input.setText(current == null || current.isEmpty() ? "http://SERVER_IP:8080/monitor.html" : current);
        input.setSelectAllOnFocus(true);
        AlertDialog.Builder b = new AlertDialog.Builder(this)
                .setTitle("Адрес Monk SKUD")
                .setMessage("Укажите адрес страницы мониторинга. Например:\nhttp://192.168.1.50:8080/monitor.html")
                .setView(input)
                .setPositiveButton("Открыть", null);
        if (!required) b.setNegativeButton("Отмена", null);
        final AlertDialog d = b.create();
        d.setOnShowListener(new DialogInterface.OnShowListener() {
            @Override public void onShow(DialogInterface dialog) {
                d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(new View.OnClickListener() {
                    @Override public void onClick(View v) {
                        String value = input.getText().toString().trim();
                        if (value.isEmpty() || value.contains("SERVER_IP")) {
                            Toast.makeText(MainActivity.this, "Введите IP или имя сервера", Toast.LENGTH_SHORT).show();
                            return;
                        }
                        load(value); d.dismiss();
                    }
                });
            }
        });
        d.setCanceledOnTouchOutside(!required);
        d.setCancelable(!required);
        d.show();
    }

    private void restartRefresh() {
        handler.removeCallbacks(refresher);
        if (active) handler.postDelayed(refresher, REFRESH_MS);
    }

    private void scheduleReload() {
        handler.postDelayed(new Runnable() {
            @Override public void run() {
                if (active && web != null) web.reload();
            }
        }, REFRESH_MS);
    }

    private void enterKioskMode() {
        getWindow().getDecorView().setSystemUiVisibility(
                View.SYSTEM_UI_FLAG_FULLSCREEN |
                View.SYSTEM_UI_FLAG_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY |
                View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION |
                View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
    }

    @Override protected void onResume() { super.onResume(); active = true; enterKioskMode(); restartRefresh(); }
    @Override public void onWindowFocusChanged(boolean hasFocus) { super.onWindowFocusChanged(hasFocus); if (hasFocus) enterKioskMode(); }
    @Override protected void onPause() { active = false; handler.removeCallbacks(refresher); super.onPause(); }
    @Override protected void onDestroy() { active = false; handler.removeCallbacks(refresher); if (web != null) web.destroy(); super.onDestroy(); }

    @Override public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_MENU) { showUrlDialog(false); return true; }
        if (keyCode == KeyEvent.KEYCODE_BACK) { return true; } // stay in kiosk
        return super.onKeyDown(keyCode, event);
    }
}
