(function(){
var listBox=null;
var lastRows='';
var lastFixedRows='';
var measureNode=null;
var serverClockUtcMs=null;
var serverClockClientMs=0;
function el(id){return document.getElementById(id);}
function esc(s){s=String(s==null?'':s);return s.replace(/[&<>\"']/g,function(c){var m={'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'};return m[c];});}
function pad2(n){return n<10?'0'+n:String(n);}
function syncServerClock(v){v=String(v||'');var m=/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2}):(\d{2})/.exec(v);if(!m)return false;serverClockUtcMs=Date.UTC(parseInt(m[1],10),parseInt(m[2],10)-1,parseInt(m[3],10),parseInt(m[4],10),parseInt(m[5],10),parseInt(m[6],10));serverClockClientMs=(new Date()).getTime();return true;}
function clockTick(){if(serverClockUtcMs===null){el('clock').innerHTML='--:--:--';el('date').innerHTML='--.--.----';return;}var elapsed=(new Date()).getTime()-serverClockClientMs;if(elapsed<0||elapsed>600000)elapsed=0;var d=new Date(serverClockUtcMs+elapsed);el('clock').innerHTML=pad2(d.getUTCHours())+':'+pad2(d.getUTCMinutes())+':'+pad2(d.getUTCSeconds());var wd=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];el('date').innerHTML=pad2(d.getUTCDate())+'.'+pad2(d.getUTCMonth()+1)+'.'+d.getUTCFullYear()+' · '+wd[d.getUTCDay()];}
function shortTime(v){v=String(v||'');return v.length>=19?v.substring(11,19):(v?v:'—');}
function statusHtml(s){if(s==='at_work')return '<span class="status present"><i class="s-dot"></i>НА РАБОТЕ</span>';if(s==='left')return '<span class="status left"><i class="s-dot"></i>УШЁЛ</span>';if(s==='disabled')return '<span class="status disabled"><i class="s-dot"></i>ОТКЛЮЧЕН</span>';return '<span class="status absent"><i class="s-dot"></i>ОТСУТСТВУЕТ</span>';}
function parseJson(text){if(window.JSON&&window.JSON.parse)return window.JSON.parse(text);return eval('('+text+')');}
function getMeasureNode(){if(measureNode)return measureNode;measureNode=document.createElement('span');measureNode.style.position='absolute';measureNode.style.left='-10000px';measureNode.style.top='-10000px';measureNode.style.visibility='hidden';measureNode.style.whiteSpace='nowrap';measureNode.style.fontFamily='Arial,Helvetica,sans-serif';document.body.appendChild(measureNode);return measureNode;}
function textWidth(text,fontSize,bold){var n=getMeasureNode();n.style.fontSize=fontSize+'px';n.style.fontWeight=bold?'bold':'normal';n.innerHTML=esc(text||'—');return n.offsetWidth||0;}
function setColWidths(widths){var cols=document.getElementsByTagName('col'),i,c,k;for(i=0;i<cols.length;i++){c=cols[i];k=String(c.className||'');if(k==='c1')c.style.width=widths[0]+'px';else if(k==='c2')c.style.width=widths[1]+'px';else if(k==='c3')c.style.width=widths[2]+'px';else if(k==='c4')c.style.width=widths[3]+'px';else if(k==='c5')c.style.width=widths[4]+'px';else if(k==='c6')c.style.width=widths[5]+'px';}}
function updateColumnWidths(rows){var wrap=el('headwrap'),total=wrap?wrap.clientWidth:0;if(total<300)return;var tall=(document.documentElement.clientHeight||document.body.clientHeight||0)>=900;var normalFont=tall?22:17,fixedFont=tall?27:20,headFont=tall?11:9,pad=tall?22:18;var statusW=Math.round(total*0.14);var posW=textWidth('ДОЛЖНОСТЬ',headFont,true)+pad;var depW=textWidth('ОТДЕЛ',headFont,true)+pad;var inW=textWidth('ПРИХОД',headFont,true)+pad;var outW=textWidth('УХОД',headFont,true)+pad;var i,r,fs,w;for(i=0;i<rows.length;i++){r=rows[i]||{};fs=(r.status==='at_work')?fixedFont:normalFont;w=textWidth(r.position||'—',fs,false)+pad;if(w>posW)posW=w;w=textWidth(r.department||'—',fs,false)+pad;if(w>depW)depW=w;w=textWidth(shortTime(r.arrival_time),fs,true)+pad;if(w>inW)inW=w;w=textWidth(shortTime(r.departure_time),fs,true)+pad;if(w>outW)outW=w;}var minEmployee=Math.max(tall?420:280,Math.round(total*0.30));var other=posW+depW+inW+outW;var available=total-statusW-minEmployee;if(other>available&&available>0){var fixedTimes=inW+outW;var roomText=available-fixedTimes;if(roomText>120){var textTotal=posW+depW;var scale=roomText/textTotal;if(scale<1){posW=Math.max(textWidth('ДОЛЖНОСТЬ',headFont,true)+pad,Math.floor(posW*scale));depW=Math.max(textWidth('ОТДЕЛ',headFont,true)+pad,Math.floor(depW*scale));}}}var employeeW=total-statusW-posW-depW-inW-outW;if(employeeW<120)employeeW=120;setColWidths([statusW,employeeW,posW,depW,inW,outW]);}
function requestJson(url,done,fail){var x;try{x=new XMLHttpRequest();}catch(e){fail('XMLHttpRequest');return;}x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{done(parseJson(x.responseText));}catch(e2){fail('JSON');}}else{fail('HTTP '+x.status);}};x.onerror=function(){fail('NETWORK');};try{x.send(null);}catch(e3){fail('SEND');}}
function renderRows(rows){var html='',i,r,cls;for(i=0;i<rows.length;i++){r=rows[i]||{};cls=(i%2?'alt ':'')+(r.status==='at_work'?'present-row':(r.status==='left'?'left-row':(r.status==='disabled'?'disabled-row':'')));html+='<tr class="'+cls+'"><td>'+statusHtml(r.status)+'</td><td class="worker-name">'+esc(r.name||'—')+'</td><td>'+esc(r.position||'—')+'</td><td class="muted">'+esc(r.department||'—')+'</td><td class="time">'+shortTime(r.arrival_time)+'</td><td class="time">'+shortTime(r.departure_time)+'</td></tr>';}return html||'<tr><td colspan="6" class="empty">Нет сотрудников</td></tr>';}
function rowsSig(rows){var s='',i,r;for(i=0;i<rows.length;i++){r=rows[i]||{};s+=String(r.id||'')+'|'+String(r.status||'')+'|'+String(r.name||'')+'|'+String(r.position||'')+'|'+String(r.department||'')+'|'+String(r.arrival_time||'')+'|'+String(r.departure_time||'')+'\n';}return s;}
function statusRank(s){if(s==='at_work')return 0;if(s==='left')return 1;if(s==='absent')return 2;if(s==='disabled')return 3;return 4;}
function compareRows(a,b){var ra=statusRank(a&&a.status),rb=statusRank(b&&b.status);if(ra!==rb)return ra-rb;var an=String(a&&a.name||'').toLowerCase(),bn=String(b&&b.name||'').toLowerCase();if(an<bn)return -1;if(an>bn)return 1;return 0;}
function layoutLists(){var base=el('headwrap').offsetTop+el('headwrap').offsetHeight;var f=el('fixedWrap');var h=(f.style.display==='none')?0:f.offsetHeight;f.style.top=base+'px';listBox.style.top=(base+h)+'px';}
function applyRowSize(tbodyId,rowH,fontSize,workerFont,statusFont){var body=el(tbodyId),tds=body?body.getElementsByTagName('td'):[],i,t,names,stats,lineH,padY;lineH=Math.max(fontSize+2,rowH-8);if(lineH>rowH-2)lineH=rowH-2;padY=Math.max(0,Math.floor((rowH-lineH)/2)-1);for(i=0;i<tds.length;i++){t=tds[i];if(String(t.className||'').indexOf('empty')>=0)continue;t.style.height=rowH+'px';t.style.fontSize=fontSize+'px';t.style.lineHeight=lineH+'px';t.style.paddingTop=padY+'px';t.style.paddingBottom=padY+'px';}names=body?body.getElementsByTagName('td'):[];for(i=0;i<names.length;i++){t=names[i];if(String(t.className||'').indexOf('worker-name')>=0)t.style.fontSize=workerFont+'px';}stats=body?body.getElementsByTagName('span'):[];for(i=0;i<stats.length;i++){t=stats[i];if(String(t.className||'').indexOf('status')>=0){t.style.fontSize=statusFont+'px';t.style.lineHeight=Math.max(statusFont+2,Math.floor(lineH*0.78))+'px';t.style.paddingTop='2px';t.style.paddingBottom='2px';}}}
function fitAllRows(fixedCount,movingCount){var card=el('tablecard'),head=el('headwrap');if(!card||!head)return;var tall=(document.documentElement.clientHeight||document.body.clientHeight||0)>=900;var base=head.offsetTop+head.offsetHeight;var available=card.clientHeight-base;if(available<80)return;var fixedDesired=tall?50:39;var movingDesired=tall?43:33;var fixedMin=tall?34:27;var movingMin=tall?20:17;var fixedRow=fixedDesired;var movingRow=movingDesired;var need=fixedCount*fixedRow+movingCount*movingRow;var remain,common;if(need>available){if(movingCount>0){movingRow=Math.floor((available-fixedCount*fixedRow)/movingCount);}if(movingRow<movingMin){movingRow=movingMin;if(fixedCount>0)fixedRow=Math.floor((available-movingCount*movingRow)/fixedCount);}if(fixedRow<fixedMin){fixedRow=fixedMin;remain=available-fixedCount*fixedRow;if(movingCount>0)movingRow=Math.floor(remain/movingCount);}if(fixedCount*fixedRow+movingCount*movingRow>available){common=Math.floor(available/Math.max(1,fixedCount+movingCount));if(fixedCount>0)fixedRow=Math.min(fixedRow,common);if(movingCount>0)movingRow=Math.min(movingRow,common);}}
if(fixedRow<16)fixedRow=16;if(movingRow<14)movingRow=14;
var fixedFont=Math.max(tall?17:14,Math.floor((tall?27:20)*fixedRow/fixedDesired));var fixedWorker=Math.max(fixedFont+1,Math.floor((tall?28:21)*fixedRow/fixedDesired));var fixedStatus=Math.max(tall?12:10,Math.floor((tall?19:15)*fixedRow/fixedDesired));var movingFont=Math.max(tall?11:10,Math.floor((tall?22:17)*movingRow/movingDesired));var movingWorker=Math.max(movingFont+1,Math.floor((tall?23:18)*movingRow/movingDesired));var movingStatus=Math.max(9,Math.floor((tall?16:13)*movingRow/movingDesired));
applyRowSize('fixedWorkers',fixedRow,fixedFont,fixedWorker,fixedStatus);layoutLists();var actualAvailable=listBox.clientHeight;if(movingCount>0&&actualAvailable>0){var byActual=Math.floor(actualAvailable/movingCount);if(byActual<movingRow){movingRow=Math.max(14,byActual);movingFont=Math.max(tall?11:10,Math.floor((tall?22:17)*movingRow/movingDesired));movingWorker=Math.max(movingFont+1,Math.floor((tall?23:18)*movingRow/movingDesired));movingStatus=Math.max(9,Math.floor((tall?16:13)*movingRow/movingDesired));}}
applyRowSize('workers',movingRow,movingFont,movingWorker,movingStatus);listBox.scrollTop=0;
}
function updateRows(rows){rows=rows||[];rows.sort(compareRows);updateColumnWidths(rows);var fixed=[],moving=[],i,r;for(i=0;i<rows.length;i++){r=rows[i]||{};if(r.status==='at_work')fixed.push(r);else moving.push(r);}var fsig=rowsSig(fixed),msig=rowsSig(moving);if(fsig!==lastFixedRows){lastFixedRows=fsig;el('fixedWorkers').innerHTML=fixed.length?renderRows(fixed):'';el('fixedWrap').style.display=fixed.length?'block':'none';}if(msig!==lastRows){lastRows=msig;el('workers').innerHTML=moving.length?renderRows(moving):(rows.length?'':'<tr><td colspan="6" class="empty">Нет сотрудников</td></tr>');}listBox.style.display=(moving.length||!rows.length)?'block':'none';layoutLists();fitAllRows(fixed.length,moving.length);}
function setConnection(ok){var c=el('connection');if(ok){c.className='online';c.innerHTML='<span class="dot"></span><b>ONLINE</b>';}else{c.className='offline';c.innerHTML='<span class="dot"></span><b>НЕТ СВЯЗИ</b>';}}
function refresh(){requestJson('/api/monitor?ts='+(new Date()).getTime(),function(j){var total=parseInt(j.registered_count,10)||0;var present=parseInt(j.present_count,10)||0;if(syncServerClock(j.generated_at))clockTick();el('presentWorkers').innerHTML=present;el('awayWorkers').innerHTML=Math.max(0,total-present);updateRows(j.workers||[]);el('updatedAt').innerHTML='Данные: '+esc(j.generated_at||'только что');setConnection(true);},function(err){el('updatedAt').innerHTML='Ошибка: '+esc(err);setConnection(false);});}
function keyHandler(e){e=e||window.event;var k=e.keyCode||e.which;if(k===13){refresh();return false;}return true;}
function init(){listBox=el('listScroll');document.onkeydown=keyHandler;window.onresize=function(){refresh();};clockTick();refresh();window.setInterval(clockTick,1000);window.setInterval(refresh,3000);}
if(document.readyState==='complete'||document.readyState==='interactive'){window.setTimeout(init,0);}else{window.onload=init;}
})();
