(function(){
var scrollBox=null;
var scrollDir=1;
var scrollPause=18;
var lastRows='';
var lastFixedRows='';
var measureNode=null;
function el(id){return document.getElementById(id);}
function esc(s){s=String(s==null?'':s);return s.replace(/[&<>\"']/g,function(c){var m={'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'};return m[c];});}
function pad2(n){return n<10?'0'+n:String(n);}
function clockTick(){var d=new Date();el('clock').innerHTML=pad2(d.getHours())+':'+pad2(d.getMinutes())+':'+pad2(d.getSeconds());var wd=['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'];el('date').innerHTML=pad2(d.getDate())+'.'+pad2(d.getMonth()+1)+'.'+d.getFullYear()+' · '+wd[d.getDay()];}
function shortTime(v){v=String(v||'');return v.length>=19?v.substring(11,19):(v?v:'—');}
function statusHtml(s){if(s==='at_work')return '<span class="status present"><i class="s-dot"></i>НА РАБОТЕ</span>';if(s==='left')return '<span class="status left"><i class="s-dot"></i>УШЁЛ</span>';if(s==='disabled')return '<span class="status disabled"><i class="s-dot"></i>ОТКЛЮЧЕН</span>';return '<span class="status absent"><i class="s-dot"></i>ОТСУТСТВУЕТ</span>';}
function parseJson(text){if(window.JSON&&window.JSON.parse)return window.JSON.parse(text);return eval('('+text+')');}
function getMeasureNode(){if(measureNode)return measureNode;measureNode=document.createElement('span');measureNode.style.position='absolute';measureNode.style.left='-10000px';measureNode.style.top='-10000px';measureNode.style.visibility='hidden';measureNode.style.whiteSpace='nowrap';measureNode.style.fontFamily='Arial,Helvetica,sans-serif';document.body.appendChild(measureNode);return measureNode;}
function textWidth(text,fontSize,bold){var n=getMeasureNode();n.style.fontSize=fontSize+'px';n.style.fontWeight=bold?'bold':'normal';n.innerHTML=esc(text||'—');return n.offsetWidth||0;}
function setColWidths(widths){var cols=document.getElementsByTagName('col'),i,c,k;for(i=0;i<cols.length;i++){c=cols[i];k=String(c.className||'');if(k==='c1')c.style.width=widths[0]+'px';else if(k==='c2')c.style.width=widths[1]+'px';else if(k==='c3')c.style.width=widths[2]+'px';else if(k==='c4')c.style.width=widths[3]+'px';else if(k==='c5')c.style.width=widths[4]+'px';else if(k==='c6')c.style.width=widths[5]+'px';}}
function updateColumnWidths(rows){var wrap=el('headwrap'),total=wrap?wrap.clientWidth:0;if(total<300)return;var tall=(document.documentElement.clientHeight||document.body.clientHeight||0)>=900;var normalFont=tall?22:17,fixedFont=tall?27:20,headFont=tall?11:9,pad=tall?22:18;var statusW=Math.round(total*0.14);var posW=textWidth('ДОЛЖНОСТЬ',headFont,true)+pad;var depW=textWidth('ОТДЕЛ',headFont,true)+pad;var inW=textWidth('ПРИХОД',headFont,true)+pad;var outW=textWidth('УХОД',headFont,true)+pad;var i,r,fs,w;for(i=0;i<rows.length;i++){r=rows[i]||{};fs=(r.status==='at_work'||r.status==='left')?fixedFont:normalFont;w=textWidth(r.position||'—',fs,false)+pad;if(w>posW)posW=w;w=textWidth(r.department||'—',fs,false)+pad;if(w>depW)depW=w;w=textWidth(shortTime(r.arrival_time),fs,true)+pad;if(w>inW)inW=w;w=textWidth(shortTime(r.departure_time),fs,true)+pad;if(w>outW)outW=w;}var minEmployee=Math.max(tall?420:280,Math.round(total*0.30));var other=posW+depW+inW+outW;var available=total-statusW-minEmployee;if(other>available&&available>0){var fixedTimes=inW+outW;var roomText=available-fixedTimes;if(roomText>120){var textTotal=posW+depW;var scale=roomText/textTotal;if(scale<1){posW=Math.max(textWidth('ДОЛЖНОСТЬ',headFont,true)+pad,Math.floor(posW*scale));depW=Math.max(textWidth('ОТДЕЛ',headFont,true)+pad,Math.floor(depW*scale));}}}var employeeW=total-statusW-posW-depW-inW-outW;if(employeeW<120)employeeW=120;setColWidths([statusW,employeeW,posW,depW,inW,outW]);}
function requestJson(url,done,fail){var x;try{x=new XMLHttpRequest();}catch(e){fail('XMLHttpRequest');return;}x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState!==4)return;if(x.status>=200&&x.status<300){try{done(parseJson(x.responseText));}catch(e2){fail('JSON');}}else{fail('HTTP '+x.status);}};x.onerror=function(){fail('NETWORK');};try{x.send(null);}catch(e3){fail('SEND');}}
function renderRows(rows){var html='',i,r,cls;for(i=0;i<rows.length;i++){r=rows[i]||{};cls=(i%2?'alt ':'')+(r.status==='at_work'?'present-row':(r.status==='left'?'left-row':(r.status==='disabled'?'disabled-row':'')));html+='<tr class="'+cls+'"><td>'+statusHtml(r.status)+'</td><td class="worker-name">'+esc(r.name||'—')+'</td><td>'+esc(r.position||'—')+'</td><td class="muted">'+esc(r.department||'—')+'</td><td class="time">'+shortTime(r.arrival_time)+'</td><td class="time">'+shortTime(r.departure_time)+'</td></tr>';}return html||'<tr><td colspan="6" class="empty">Нет сотрудников</td></tr>';}
function rowsSig(rows){var s='',i,r;for(i=0;i<rows.length;i++){r=rows[i]||{};s+=String(r.id||'')+'|'+String(r.status||'')+'|'+String(r.name||'')+'|'+String(r.position||'')+'|'+String(r.department||'')+'|'+String(r.arrival_time||'')+'|'+String(r.departure_time||'')+'\n';}return s;}
function statusRank(s){if(s==='at_work')return 0;if(s==='left')return 1;if(s==='absent')return 2;if(s==='disabled')return 3;return 4;}
function compareRows(a,b){var ra=statusRank(a&&a.status),rb=statusRank(b&&b.status);if(ra!==rb)return ra-rb;var an=String(a&&a.name||'').toLowerCase(),bn=String(b&&b.name||'').toLowerCase();if(an<bn)return -1;if(an>bn)return 1;return 0;}
function layoutLists(){var base=el('headwrap').offsetTop+el('headwrap').offsetHeight;var f=el('fixedWrap');var h=(f.style.display==='none')?0:f.offsetHeight;f.style.top=base+'px';scrollBox.style.top=(base+h)+'px';}
function updateRows(rows){rows=rows||[];updateColumnWidths(rows);var fixed=[],moving=[],i,r;for(i=0;i<rows.length;i++){r=rows[i]||{};if(r.status==='at_work'||r.status==='left')fixed.push(r);else moving.push(r);}fixed.sort(compareRows);moving.sort(compareRows);var fsig=rowsSig(fixed),msig=rowsSig(moving);if(fsig!==lastFixedRows){lastFixedRows=fsig;el('fixedWorkers').innerHTML=renderRows(fixed);el('fixedWrap').style.display=fixed.length?'block':'none';}if(msig!==lastRows){lastRows=msig;el('workers').innerHTML=renderRows(moving);scrollBox.scrollTop=0;scrollDir=1;scrollPause=18;}layoutLists();}
function setConnection(ok){var c=el('connection');if(ok){c.className='online';c.innerHTML='<span class="dot"></span><b>ONLINE</b>';}else{c.className='offline';c.innerHTML='<span class="dot"></span><b>НЕТ СВЯЗИ</b>';}}
function refresh(){requestJson('/api/monitor?ts='+(new Date()).getTime(),function(j){var total=parseInt(j.registered_count,10)||0;var present=parseInt(j.present_count,10)||0;el('presentWorkers').innerHTML=present;el('awayWorkers').innerHTML=Math.max(0,total-present);updateRows(j.workers||[]);el('updatedAt').innerHTML='Данные: '+esc(j.generated_at||'только что');setConnection(true);},function(err){el('updatedAt').innerHTML='Ошибка: '+esc(err);setConnection(false);});}
function scrollStep(){if(!scrollBox)return;var max=scrollBox.scrollHeight-scrollBox.clientHeight;if(max<5){scrollBox.scrollTop=0;scrollDir=1;scrollPause=18;return;}if(scrollPause>0){scrollPause--;return;}if(scrollDir>0){scrollBox.scrollTop=scrollBox.scrollTop+4;if(scrollBox.scrollTop>=max-4){scrollBox.scrollTop=max;scrollDir=-1;scrollPause=22;}}else{scrollBox.scrollTop=0;scrollDir=1;scrollPause=16;}}
function keyHandler(e){e=e||window.event;var k=e.keyCode||e.which;if(k===38){scrollBox.scrollTop=Math.max(0,scrollBox.scrollTop-60);scrollPause=40;return false;}if(k===40){scrollBox.scrollTop=Math.min(scrollBox.scrollHeight-scrollBox.clientHeight,scrollBox.scrollTop+60);scrollPause=40;return false;}if(k===13){refresh();return false;}return true;}
function init(){scrollBox=el('listScroll');document.onkeydown=keyHandler;window.onresize=function(){refresh();};clockTick();refresh();window.setInterval(clockTick,1000);window.setInterval(refresh,3000);window.setInterval(scrollStep,100);}
if(document.readyState==='complete'||document.readyState==='interactive'){window.setTimeout(init,0);}else{window.onload=init;}
})();
